server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://dreamstartcloud.top:3306/codetrain-data?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: '!12Mengqiyun'
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_

